import p1 from '../_metronic/assets/avatars/1.jpg'
import p2 from '../_metronic/assets/avatars/2.jpg'
import p3 from '../_metronic/assets/avatars/3.jpg'
import p4 from '../_metronic/assets/avatars/4.jpg'
import p5 from '../_metronic/assets/avatars/5.jpg'
export const IMAGES = {
  WadsworthDistributorsLtd: require('../_metronic/assets/brand/wadsworth-distributors-limited.png'),
  ElvenAgri: require('../_metronic/assets/brand/elven_agri.png'),
  SuperMealsLtd: require('../_metronic/assets/brand/super_meal.png'),
  CoolBlue: require('../_metronic/assets/brand/cool_blue.png'),
  MacLeansBeneCIBOLtd: require('../_metronic/assets/brand/macLeans.png'),
  Afribon: require('../_metronic/assets/brand/afribon.png'),
  KilimoFreshFoodsAfricaLTD: require('../_metronic/assets/brand/kilimo.png'),
  ZamzamStationerySupermarket: require('../_metronic/assets/brand/zamzam.png'),
  NilePerchFisheriesLtd: require('../_metronic/assets/brand/nile_perch.png'),
  OmrosFoods: require('../_metronic/assets/brand/omros_foods.png'),
  NutroWafer: require('../_metronic/assets/food/chochlate.png'),
  LatoMilk: require('../_metronic/assets/food/milk.png'),
  RollGum: require('../_metronic/assets/food/pop.png'),
  AmazonMonstaPops: require('../_metronic/assets/food/strawberry.png'),
  FreedomPen: require('../_metronic/assets/food/pen.png'),
}
export const MyTeam = [
  {
    image: p1,
    name: 'Patrick Richards',
    customer: '10',
    orders: '06',
    sales: 'Tsh 132,300',
  },
  {
    image: p2,
    name: 'Bianca Ross',
    customer: '07',
    orders: '11',
    sales: 'Tsh 5,313,214',
  },
  {
    image: p3,
    name: 'Matthew Powell',
    customer: '03',
    orders: '02',
    sales: 'Tsh 45,212',
  },
  {
    image: p4,
    name: 'Aunali Mohamed Abdulrazak',
    customer: '09',
    orders: '07',
    sales: 'Tsh 237,500 ',
  },
]
export const BrandAndTotalSales = [
  {
    brandImage: IMAGES.WadsworthDistributorsLtd,
    brandName: 'Wadsworth Distributors Limited',
    customerName: 'Patrick Richards',
    ordersPlaced: '06',
    quantity: '23 items',
    totalSales: 'Tsh 132,300',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '25/03/23 - 21:30',
    code: '#00982',
    orderBy: 'Customer',
    commissionEarned: '1,794,435',
    paymentsCompleted: '7,236,500',
    paymentsDue: '3,319,000',
  },
  {
    brandImage: IMAGES.Afribon,
    brandName: 'Aftibon',
    customerName: 'Alan Diaz',
    totalSales: 'Tsh 9,513,214',
    totalAmount: 'Tsh 311,500',
    dateTime: '25/03/23 - 21:30',
    code: '#00981',
    quantity: '12 items',
    ordersPlaced: '11',
    orderBy: 'Customer',
    commissionEarned: '1,426,982',
    paymentsCompleted: '5,520,047',
    paymentsDue: '3,993,167',
  },
  {
    brandImage: IMAGES.KilimoFreshFoodsAfricaLTD,
    brandName: 'Kilimo Fresh Foods',
    customerName: 'Laurel Oliver  ',
    totalSales: 'Tsh 7,767,500',
    quantity: '27 items',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '25/03/23 - 10:42 ',
    orderBy: 'Nalla Okafor',
    code: '#00980',
    ordersPlaced: '02',
    commissionEarned: '932,100',
    paymentsCompleted: '5,500,531',
    paymentsDue: '2,266,969',
  },
  {
    brandImage: IMAGES.CoolBlue,
    brandName: 'Cool Blue',
    totalSales: 'Tsh 5,450,384',
    ordersPlaced: '07',
    quantity: '23 items',
    orderBy: 'Customer',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '24/03/23 - 15:10',
    code: '#00979',
    customerName: 'Denise Jones',
    commissionEarned: '545,038',
    paymentsCompleted: '5,230,072',
    paymentsDue: '220,312',
  },
  {
    brandImage: IMAGES.OmrosFoods,
    brandName: 'Omros Foods',
    totalSales: 'Tsh 8,500,333',
    quantity: '19 items',
    ordersPlaced: '05',
    totalAmount: 'Tsh 1,000,000',
    orderBy: 'Nalla Okafor',
    dateTime: '24/03/23 - 15:03',
    code: '#00978',
    customerName: 'Matthew Powell',
    commissionEarned: '266,502',
    paymentsCompleted: '1,750,047',
    paymentsDue: '299,973',
  },
  {
    brandImage: IMAGES.SuperMealsLtd,
    brandName: 'Super Meals Limited',
    customerName: 'Barbara Mendoza',
    quantity: '06 items',
    ordersPlaced: '15',
    orderBy: 'Nalla Okafor',
    totalSales: 'Tsh 1,137,982',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '24/03/23 - 09:56',
    code: '#00976',
    commissionEarned: '91,038',
    paymentsCompleted: '955,321',
    paymentsDue: '182,661',
  },
  {
    brandImage: IMAGES.MacLeansBeneCIBOLtd,
    brandName: 'MacLeans Bene CIBO Ltd',
    customerName: 'Kathy Clark',
    totalSales: 'Tsh 1,050,000',
    quantity: '06 items',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '23/03/23 - 18:10',
    orderBy: 'Nalla Okafor',
    code: '#00975',
    ordersPlaced: '12',
    commissionEarned: '88,399',
    paymentsCompleted: '0',
    paymentsDue: '982,217',
  },
  {
    brandImage: IMAGES.ZamzamStationerySupermarket,
    brandName: 'Zamzam Stationery Supermarket',
    totalSales: 'Tsh 900,000',
    customerName: 'Patrick Richards',
    orderBy: 'Customer',
    quantity: '12 items',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '23/03/23 - 17:25',
    code: '#00974',
    ordersPlaced: '12',
    commissionEarned: '112,573',
    paymentsCompleted: '45,212',
    paymentsDue: '45,212',
  },
  {
    brandImage: IMAGES.NilePerchFisheriesLtd,
    brandName: 'Nile Perch Fisheries Ltd',
    totalSales: 'Tsh 20,500',
    quantity: '27 items',
    customerName: 'Barbara Mendoza',
    totalAmount: 'Tsh 1,000,000',
    dateTime: '22/03/23 - 15:10',
    orderBy: 'Customer',
    code: '#00973',
    commissionEarned: '42,009',
    ordersPlaced: '08',
    paymentsCompleted: '720,350',
    paymentsDue: '30,140',
  },
  {
    brandImage: IMAGES.ElvenAgri,
    brandName: 'Elven Agri',
    totalSales: 'Tsh 250,500',
    customerName: 'Bianca Ross',
    quantity: '6 items',
    ordersPlaced: '06',
    commissionEarned: '55,094',
    orderBy: 'Customer',
    totalAmount: 'TSh 225,000',
    dateTime: '22/03/23 - 12:18',
    code: '#00972',
    paymentsCompleted: '503,897',
    paymentsDue: '47,051',
  },
]
export const ProductDetails = {
  records: [
    {
      productImage: IMAGES.NutroWafer,
      productDescription: 'Nutro Wafer Biscuits (Chocolate, 75g)',
      productCompany: 'Wadsworth Distributors Limited',
      unitPrice: 'Tsh 53,000',
      quantityType: '10 X Cartons',
      totalAmount: 'Tsh 1,007,000',
    },
    {
      productImage: IMAGES.RollGum,
      productDescription: 'Amazon Roll Gum',
      productCompany: 'Super Meals Limited',
      unitPrice: 'Tsh 12,000',
      quantityType: '25 X Cartons',
      totalAmount: 'Tsh 300,000',
    },
    {
      productImage: IMAGES.AmazonMonstaPops,
      productDescription: 'Amazon Monsta Pops (Strawberry)',
      productCompany: 'MacLeans BeneCIBO Limited',
      unitPrice: 'Tsh 9,500',
      quantityType: '15 X Dozens',
      totalAmount: 'Tsh 142,500',
    },
    {
      productImage: IMAGES.FreedomPen,
      productDescription: 'Freedom Ball Pen',
      productCompany: 'Afribon',
      unitPrice: 'TSh 1,150',
      quantityType: '100 X Pieces',
      totalAmount: 'TSh 115,000',
    },
  ],
  basicDetails: {
    customerName: 'Patrick Richards',
    orderId: '#00982',
    orderPlaced: '25/03/23 - 21:30',
    paymentMethod: 'Tigo pesa',
  },
  deliveryDetails: {
    shopName: 'Maisha Supermarket',
    phoneNumber: '+255 657 727 427',
    deliveryAddress: 'Kibada St, Dar es Salaam, Tanzania',
    city: 'Kigamboni, Dar es Salaam',
  },
  subTotal: 'Tsh 2,294,500',
  tax: 'Tsh 45,890',
  grandTotal: 'Tsh 2,340,390',
}
